version: "3.8"

services:
  gemini-db:
    image: postgres:13
    container_name: gemini-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gemini-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    # 実行したSQLを標準出力に吐きたい場合
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
  grpc:
    tty: true
    depends_on:
      - gemini-db
    container_name: gemini
    build:
      context: .
      target: "development"
    ports:
      - "9020:9020"
    # environment:
    #   DATABASE_URL: gemini-db
    #   DATABASE_PORT: 5432
    #   DATABASE_USER: gemini
    #   DATABASE_PASSWORD: gemini
    #   DATABASE_NAME: gemini-db
    #   LISTEN_PORT: ":9020"
    volumes:
      - type: bind
        source: .
        target: /gemini

volumes:
  db_data:
