version: "3.8"

services:
  gemini:
    tty: true
    container_name: gemini
    build:
      context: .
      target: "development"
    ports:
      - "9020:9020"
    environment:
      SECRET: "!!!secret!!!"
      EXPIRE: 3600
    volumes:
      - type: bind
        source: .
        target: /gemini
